# Generated by Django 2.2 on 2019-04-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
